services:
  - type: web
    name: web
    env: python
    envVars:
      - key: SECRET_KEY
        value: 'your_secret_key_here'
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --workers 3"
